# Generated by Django 4.2.11 on 2024-06-15 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_venta_departamento_venta_giro_venta_municipio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="existencia",
            name="detalle_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tienda.detalleventa",
            ),
        ),
    ]
