# Generated by Django 4.2.11 on 2024-06-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0006_alter_detalleventa_existencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="existencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalleventa_set",
                to="tienda.existencia",
            ),
        ),
    ]
