# Generated by Django 4.2.11 on 2024-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0008_alter_venta_metodo_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TARJETA", "Tarjeta"),
                    ("DEPOSITO", "Deposito Bancario"),
                    ("GIRO", "Remesa"),
                    ("BITCOIN", "Bitcoin"),
                ],
                default="EFECTIVO",
                max_length=50,
            ),
        ),
    ]
