# Generated by Django 4.2.11 on 2024-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0009_alter_venta_metodo_pago"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                ("rubro", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "representante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
