# Generated by Django 4.2.11 on 2024-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0011_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="existencia",
            name="fechaIngreso",
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="existencia",
            name="nfacturaCompra",
            field=models.CharField(default="Sin orden de compra", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="existencia",
            name="nombreProveedor",
            field=models.CharField(default="Sin info", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="existencia",
            name="ordenCompra",
            field=models.CharField(default="NA", max_length=100),
            preserve_default=False,
        ),
    ]
