# Generated by Django 4.2.11 on 2024-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0012_existencia_fechaingreso_existencia_nfacturacompra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="existencia",
            name="caux1",
            field=models.CharField(default="sin info", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="existencia",
            name="caux2",
            field=models.CharField(default="Sin info", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="existencia",
            name="caux3",
            field=models.CharField(default="Sin info", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="existencia",
            name="observaciones",
            field=models.CharField(default="Sin info", max_length=500),
            preserve_default=False,
        ),
    ]
