# Generated by Django 4.2.11 on 2024-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0013_existencia_caux1_existencia_caux2_existencia_caux3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="existencia",
            name="lote",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="existencia",
            name="fechaIngreso",
            field=models.DateField(),
        ),
    ]
