# Generated by Django 4.2.11 on 2024-06-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0015_usuario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="password",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefono",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(default="Sin nombre", max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="departamento",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
