# Generated by Django 4.2.11 on 2024-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0016_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
    ]
