# Generated by Django 4.2.11 on 2024-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0017_usuario_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="vendedor",
            field=models.CharField(default="Sin nombre", max_length=100),
        ),
    ]
