# Generated by Django 4.2.11 on 2024-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0018_venta_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="existencia",
            name="operador",
            field=models.CharField(default="Admin", max_length=100),
        ),
    ]
