# Generated by Django 4.2.11 on 2024-06-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0020_existencia_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="existencia",
            name="cantidad",
            field=models.IntegerField(default=1),
        ),
    ]
